# Uma revisão de Algebra Linear com Python

Muitas áreas da Ciência da Computação trazem como requisito algum conhecimento de álgebra linear, seja direta ou indiretamente. Pela própria forma com que essas áreas interagem com álgebra linear, muita coisa pode ser entendida de forma indireta sem nunca se aprofundar diretamente nessa área da matemática.  
Algumas dessas áreas são **Machine Learning**, **Deep Learning**, **processamento de imagens**, etc.  
Para fazer uma revisão de Álgebra Linear em um contexto de computação então fazemos uso de uma linguagem de programação que é porta de entrada para essas áreas: **Python**, principalmente suas bibliotecas com foco matemático maior como **Numpy** e **Scipy**.

In [ ]:
import numpy as np
from scipy import linalg
import tensorflow as tf


## Motivação: mil nomes para as mesmas coisas

Muitas coisas na fronteira entre Ciência da Computação e Matemática podem ter nomes diferentes mesmo sendo iguais e nomes iguais mesmo sendo diferentes. Vamos ver algumas delas e como isso se relaciona com Álgebra Linear

### Matrizes, arrays, listas, vetores

Matrizes são uma daquelas coisas que pode ter vários nomes na computação dependendo para onde você for. De forma prática, uma **matriz** é uma tabela de elementos dispostos em linhas e colunas, sendo cada elemento um número.  
Formalmente:  

````{prf:definition}
Uma *matriz* $m \times n$ sobre um corpo $F$ é uma função $A$ do par de inteiros $(i, j)$, com $1 \leq i \leq m, 1 \leq j \leq n$, no corpo $F$. Sendo cada elemento um *escalar* representado por $A(i, j) = A_{ij}$. [Hoff71]
````

(Se você não entendeu nada e não sabe o que é um "corpo" e tudo mais, calma que é normal, essa definição vai ficar mais clara no decorrer do texto).

Para simbolizar uma matriz em uma linguagem de programação é utilizada a noção de *Array*, traduzida normalmente por *vetor*. Normalmente um array é uma matriz $1 \times m$, ou seja, uma matriz de 1 linha e m colunas. Arrays de mais de uma linha são chamados de *multidimensional arrays*, ou simplesmente matrizes.  
Em linguagens de alto nível como python, o conceito de arrays e lista se confunde e, diferente da definição matemática de matrizes, os arrays em python não tem tamanho limite explícito.  
Em C, por exemplo, arrays possuem tamanho limite (na verdade se forem alocados não, mas isso é outro texto). Por exemplo, uma matriz quadrada $2 \times 2$ é representada por:
``` C
int matrizQuadrada[2][2];
// ou se você quiser alocar diretamente:
int **matrizQuadrada = (int **)malloc(2 * sizeof(int *));
for(int i = 0; i < m; i++) matrizQuadrada[i] = (int *)malloc(2 * sizeof(int));
```
Em python, para alocar um array podemos utilizar as listas nativas da linguagem:




In [ ]:
# Lista nativa:
matriz_quadrada = [[1, 2],
                  [3, 4]]

# Codigo para acessar cada elemento:
m = len(matriz_quadrada)
n = len(matriz_quadrada[1])
for i in range(m):
  for j in range(n):
    print('a{}{} = {} '.format(i, j, matriz_quadrada[i][j]), end="")
  print('')


a00 = 1 a01 = 2 
a10 = 3 a11 = 4 


Uma questão que surge com as listas de Python, principalmente voltado para computação mais pesada, é que elas são lentas demais em algumas questões. Então, normalmente, utilizamos as listas de numpy para criar arrays mais eficientes.  

In [ ]:
# Lista em Numpy
matriz_quadrada_eficiente = np.array([[2, 4], [6, 8]])

# Codigo para acessar cada elemento
m = len(matriz_quadrada_eficiente)
n = len(matriz_quadrada_eficiente[0])
for i in range(m):
  for j in range(n):
    print('a{}{} = {} '.format(i, j, matriz_quadrada_eficiente[i, j]), end="")
  print('')


a00 = 2 a01 = 4 
a10 = 6 a11 = 8 


### Tipos de Matrizes

As operações e definições de matrizes vão ser mostradas quando entrar na definição de Espaço Vetorial. Mas por enquanto vamos definir alguns tipos de matrizes que serão úteis [Bold86]:

1. Matriz Quadrada: matriz cujo número de linhas e de colunas é o mesmo ($m = n$)
2. Matriz Nula: matriz onde todos os elementos são zero ($\forall i \forall j (a_{ij} = 0)$)
3. Matriz-Coluna: matriz que só possui 1 coluna, $n=1$ ou $m \times 1$
4. Matriz-Linha (na computação, array unidimensional): matriz que só possui 1 linha, $m=1$ ou $1 \times n$
5. Matriz Diagonal: matriz quadrada onde $a_{ij}=0$ se $i \neq j$.
6. Matriz Identidade: matriz quadrada representada por $I_m$ com elementos definidos por: $$a{ij} = \begin{cases} 
      1 & i = j \\
      0 & i \neq j
   \end{cases}
$$

Em numpy, algumas delas podem ser definidas por:

In [ ]:
# Matriz (quadrada) Nula)
matriz_nula = np.zeros((2, 2))
matriz_nula

array([[0., 0.],
       [0., 0.]])

In [ ]:
# Matriz diagonal
matriz_diagonal = np.diag([1, 2, 3])
print(matriz_diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
# Matriz identidade
matriz_identidade = np.eye(2)
print(matriz_identidade)

[[1. 0.]
 [0. 1.]]


### Um pequeno detour para falar de Tensores

Bibliotecas de Machine Learning como TensorFlow utilizam estruturas chamadas de *tensores* para construir seus modelos. É aqui que coisas diferentes possuem o mesmo nome. Nesse ponto não vale a pena puxar a definição matemática de tensores porque ela utiliza termos e outras definições que ainda não foram introduzidas, mas a definição de tensores em TensorFlow é a mesma da de uma matriz, só tendo diferença em sua execução.  
A diferença entre tensores e arrays de numpy é que tensores não podem ter sua dimensão nem seus valores modificados. Os tensores de tensorflow são divididos em ranks:
1. Rank 0 (escalar): corresponde aos escalares ou matrizes 1x1
2. Rank 1 (vetor): corresponde aos vetores unidimensionais (matriz linha)
3. Rank 2 (matriz): corresponde a uma matriz $m \times n$


In [ ]:
rank_0_tensor = tf.constant(4)
print("rank 0: {}".format(rank_0_tensor))

rank_1_tensor = tf.constant([2, 3, 4])
print("rank 1: {}".format(rank_1_tensor))

rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]])
print("rank 2: {}".format(rank_2_tensor))

rank 0: 4
rank 1: [2 3 4]
rank 2: [[1 2]
 [3 4]
 [5 6]]


## Bibliografia
[Bold86] - Boldrini, J. L. Algebra Linear. Harbra, 1986.  
[Hoff71] - Hoffman, K.M and Kunze, R. Linear Algebra. Prentice Hall, 1971.